# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      $file = "$(Build.SourcesDirectory)/config.json"
      $json = (Get-Content -Path $file | Out-String | ConvertFrom-Json)
      $version = $json.version
      Write-Host "##vso[task.setvariable variable=version]$(version)"
      Write-Host "Version: $version"
  displayName: 'Read version from config file'
