# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  - group: docker
  - name: versionBuilder
    value: '2.0'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      $file = "$(Build.SourcesDirectory)/config.json"
      $json = (Get-Content -Path $file | Out-String | ConvertFrom-Json)
      Write-Host "$json"
      $version = $json.version
      Write-Host "##vso[task.setvariable variable=version]$version"
      Write-Host "Version: $version"
  displayName: 'Read version from config file'

- task: Docker@2
  inputs:
    command: login
    containerRegistry: dockerhub
  displayName: Login to Docker Hub
- task: PowerShell@2
  inputs:
    targetTYpe: 'inline'
    script: sudo docker pull homeassistant/amd64-builder:$(versionBuilder)
  displayName: 'Install Builder'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      sudo docker run --rm --privileged \
        -v ~/.docker:/root/.docker \
        -v /my_addon:/data homeassistant/amd64-builder \
        -t $(Build.SourcesDirectory) \
        --all \
        --docker-hub-check

  displayName: 'Build images'
